on:
  push:
    branches:
      - main
    
jobs:
  render:
    name: Render all READMEs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("purrr", "quarto", "here", "fs"))'
      - name: Render READMEs
        run: Rscript render_READMEs.R
      - name: Commit results
        run: |
          git config --global user.email "culshawmaurer@arizona.edu"
          git config --global user.name "Michael Culshaw-Maurer"
          git add --force */README.md
          git add --force */README_files/
          git commit -m 'Render READMEs' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
