on:
  push:
    branches:
      - main

jobs:
  render:
    name: Render all READMEs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install openssl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install libxml2
        run:  sudo apt-get install libxml2-dev
      - name: Install packages
        run: Rscript -e 'install.packages("quarto")'
      - name: Render READMEs
        run: Rscript render_READMEs.R
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: README rendering bot
